pipeline {
	agent any
	stages{
		stage('Execute Pom.xml file'){
			steps{
				script{
					dir('C:\\Users\\mmohamedkm\\git\\RestAssuredAutomation\\RestAssuredAutomation') {
						bat 'run.bat'
					}
				}
			}
		}
		stage('Generate Allure Report') {
			steps {
				script {
					ws('C:/Users/mmohamedkm/git/RestAssuredAutomation/RestAssuredAutomation') {
						allure([
						        includeProperties: false,
						        jdk: '',
						        properties: [],
						        reportBuildPolicy: 'ALWAYS',
						        results: [[path: 'allure-results']]
						        		])
					}
				}
			}
		}
	}
}